# Generated by Django 2.1.7 on 2020-03-25 03:42

from django.db import migrations, models
import django.db.models.deletion
import grsApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceDetails',
            fields=[
                ('griev_detail_id', models.CharField(default=grsApp.models.create_grievance_detail_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('griev_status', models.CharField(max_length=45, null=True)),
                ('griev_status_desc', models.CharField(max_length=255, null=True)),
                ('griev_st_desc_up_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grievances',
            fields=[
                ('griev_id', models.CharField(default=grsApp.models.create_grievance_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('griev_title', models.CharField(max_length=45)),
                ('griev_desc', models.CharField(max_length=255)),
                ('griev_filed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrievanceTypes',
            fields=[
                ('griev_type_id', models.CharField(default=grsApp.models.create_grievance_type_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('griev_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='grievances',
            name='griev_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grsApp.GrievanceTypes'),
        ),
        migrations.AddField(
            model_name='grievancedetails',
            name='griev_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grsApp.Grievances'),
        ),
    ]
